// Code generated by scripts/gen_sms_capabilities.go. DO NOT EDIT.

package sms

// Auto-generated provider registry
func init() {
	
	RegisterProviderConstructor(ProviderTypeAliyun, NewAliyunProvider)
	
	RegisterProviderConstructor(ProviderTypeCl253, NewCl253Provider)
	
	RegisterProviderConstructor(ProviderTypeYuntongxun, NewYuntongxunProvider)
	
	RegisterProviderConstructor(ProviderTypeJuhe, NewJuheProvider)
	
	RegisterProviderConstructor(ProviderTypeHuawei, NewHuaweiProvider)
	
	RegisterProviderConstructor(ProviderTypeVolc, NewVolcProvider)
	
	RegisterProviderConstructor(ProviderTypeSmsbao, NewSmsbaoProvider)
	
	RegisterProviderConstructor(ProviderTypeSubmail, NewSubmailProvider)
	
	RegisterProviderConstructor(ProviderTypeUcp, NewUcpProvider)
	
	RegisterProviderConstructor(ProviderTypeLuosimao, NewLuosimaoProvider)
	
	RegisterProviderConstructor(ProviderTypeYunpian, NewYunpianProvider)
	
	RegisterProviderConstructor(ProviderTypeTencent, NewTencentProvider)
	
}
